.\"
.\" Copyright (C) 2008, 2009 Loic Dachary <loic@dachary.org>
.\"
.\" This software's license gives you freedom; you can copy, convey,
.\" propagate, redistribute and/or modify this program under the terms of
.\" the GNU Affero General Public License (AGPL) as published by the Free
.\" Software Foundation, either version 3 of the License, or (at your
.\" option) any later version of the AGPL.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU Affero General Public License
.\" along with this program in a file in the toplevel directory called
.\" "AGPLv3".  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH pokerdatabase 5 local
.SH NAME
pokerdatabase \- structure of the poker-network SQL database

.SH DESCRIPTION

The poker-network server stores persisten information in a MySQL database which
is usually named 
.I pythonpokernetwork

Documentation on the purpose of each table and their fields may be found in the
.I NONE/share/poker-network/database/schema.sql
file.

The purpose of this manual page is to provide information on how the tables and fields
are used by the poker server.

.SH PLAYERS

The poker server provides support for a complete poker player
description, including personal information such as address and phone
number. However, the server was designed to be mixed with external
user databases. For this purpose the player information is split in
two tables :
.I users
and
.I users_private

For each player there must be a unique record in the 
.I users 
table. There may be an optional record in the
.I users_private
table. If the
.I users_private
record is missing, the client must not send the following packets:
.I PacketPokerSetAccount, PacketPokerGetPlayerInfo
otherwise the server will fail.

A third party application can create a player by inserting a new record
with the following fields set : a unique
.I name,
a unique 
.I email
and a 
.I password.

If a record is added in the
.I users_private 
table, clients using the
.I PacketPokerSetAccount, PacketPokerGetPlayerInfo
packets will be able to join. The 
.I users_private 
record has only one required field, the
.I serial
number of the associated record in the 
.I users
table.

.SH TOURNAMENTS

The 
.I tourneys_schedule 
table has one row for each scheduled tournament. The server will poll the table every
5 minutes to check for new rows.

.SH AUTHORS

Loic Dachary <loic@dachary.org>

.\" Local Variables:
.\" compile-command: "( cd .. ; config.status database/pokerdatabase.5 ) ; nroff -man pokerdatabase.5 | col -b"
.\" End:
