package Room::Model::PokerNetwork;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
);

=head1 NAME

Room::Model::PokerNetwork - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Room>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Room::Schema::PokerNetwork>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

Pavel Karoukin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

use Moose;
use Cache::Memcached;

our $pokernetwork_memcache;

sub BUILD {
  my $self = shift;

  $self->{pokernetwork_memcache} = new Cache::Memcached {
    'servers' => [
      $self->{pokernetwork_memcache_servers}
    ],
  };
}

sub get_user_id_by_auth {
  my ($self, $auth) = @_;

  return $self->{pokernetwork_memcache}->get($auth);
}

sub set_user_id_by_auth {
  my ($self, $user_id, $auth) = @_;

  return $self->{pokernetwork_memcache}->set($auth, $user_id);
}

sub logout {
  my ($self, $auth) = @_;

  return $self->{pokernetwork_memcache}->delete($auth);
}

1;
