#!/bin/sh
#
# Copyright (C) 2007, 2008, 2009 Loic Dachary <loic@dachary.org>
# Copyright (C) 2004, 2005, 2006 Mekensleep <licensing@mekensleep.com>
#                                24 rue vieille du temple, 75004 Paris
#
# This software's license gives you freedom; you can copy, convey,
# propagate, redistribute and/or modify this program under the terms of
# the GNU Affero General Public License (AGPL) as published by the Free
# Software Foundation (FSF), either version 3 of the License, or (at your
# option) any later version of the AGPL published by the FSF.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program in a file in the toplevel directory called
# "AGPLv3".  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#  Loic Dachary <loic@dachary.org>
#
set -e 

: ${srcdir:=.}

SCHEMA=$srcdir/schema.sql

. $srcdir/createdatabase

/usr/bin/python ${srcdir}/coverage.py -x  ../database/pokerdatabaseupgrade --dry-run --upgrades=$srcdir/../database $srcdir/poker.server.xml
/usr/bin/python ${srcdir}/coverage.py -x ../database/pokerdatabaseupgrade --upgrades=$srcdir/../database $srcdir/poker.server.xml
trap "rm -fr conftest" EXIT
rm -fr conftest ; mkdir -p conftest
export PYTHONPATH=$srcdir/..
/usr/bin/python ${srcdir}/coverage.py -x /usr/local/sbin/pokerconfigupgrade --verbose=1 --reference=$srcdir/conf conftest
chmod u+w conftest
/usr/bin/python ${srcdir}/coverage.py -x /usr/local/sbin/pokerconfigupgrade --verbose=1 --module=pokernetwork.pokernetworkconfig --upgrades=$srcdir/../upgrades/poker.bot conftest/poker.bot.xml.in
/usr/bin/python ${srcdir}/coverage.py -x /usr/local/sbin/pokerconfigupgrade --verbose=1 --module=pokernetwork.pokernetworkconfig --upgrades=$srcdir/../upgrades/poker.server conftest/poker.server.xml.in

# Interpreted by emacs
# Local Variables:
# compile-command: "( cd .. ; ./config.status tests/upgrade.py ) ; ( cd ../tests ; make TESTS='upgrade' check )"
# End:
